fix: gotsd

diff --git a/.github/workflows/main_push_tagger.yml b/.github/workflows/main_push_tagger.yml
--- a/.github/workflows/main_push_tagger.yml
+++ b/.github/workflows/main_push_tagger.yml
@@ -17,14 +17,19 @@ jobs:
       - name: Determine the previous version
         id: previous_version
         run: |
-          PREVIOUS_VERSION=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.tag_name' | sed 's/v//')
-          PR_NUMBER="${{ github.event.number }}"
-          PR_BRANCH="v${PREVIOUS_VERSION}-dev.${PR_NUMBER}"
-          echo "PREVIOUS_VERSION=${PREVIOUS_VERSION}" >> $GITHUB_ENV
-          echo "PR_BRANCH=${PR_BRANCH}" >> $GITHUB_ENV
+          LATEST_TAG=$(git describe --tags --abbrev=0)
+          # Remove the "v" prefix if it exists
+          PREVIOUS_VERSION=${LATEST_TAG#v}
+          if [[ $PREVIOUS_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            PR_NUMBER="${{ github.event.number }}"
+            PR_BRANCH="${PREVIOUS_VERSION}-dev.${PR_NUMBER}"
+            echo "PREVIOUS_VERSION=${PREVIOUS_VERSION}" >> $GITHUB_ENV
+            echo "PR_BRANCH=${PR_BRANCH}" >> $GITHUB_ENV
+          else
+            echo "Error: Invalid previous version format."
+            exit 1
+          fi
         continue-on-error: true
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Tag commits in PR
         run: |
@@ -44,7 +49,7 @@ jobs:
               git checkout master
               git pull
               git merge "$PR_BRANCH" --no-ff -m "Merge PR $PR_BRANCH"
-              git tag -a -m "Release $PREVIOUS_VERSION" "v$PREVIOUS_VERSION"
+              git tag -a -m "Release $PREVIOUS_VERSION" "$PREVIOUS_VERSION"
               git push origin master --tags
               git push origin --delete "$PR_BRANCH"
             fi
